// alunos.js - Dados dos alunos cadastrados
// Data de referência: 31/12/2026

const ALUNOS_CADASTRADOS = [
  // ==================== VOLEI MISTO - SUB 15/17 ====================
  // Segunda-feira 9:30 as 10:50
  {
    id: 1,
    nome: "EMERSON PEREIRA SILVA",
    cpf: "10086297589", // ✓ Confirmado na lista
    dataNascimento: "2013-03-01",
    sexo: "Masculino",
    turma: "8º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Segunda", horario: "09h30-10h50" }],
    modalidades: ["vôlei misto"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.5,
    foto: "",
  },
  {
    id: 2,
    nome: "LUCIELE SANTOS OLIVEIRA",
    cpf: "86484219508", // ✓ Confirmado na lista
    dataNascimento: "2011-05-14",
    sexo: "Feminino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Segunda", horario: "09h30-10h50" }],
    modalidades: ["vôlei misto"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 9.0,
    foto: "",
  },

  // ==================== BALEADO FEMININO - SUB 13 ====================
  // Quarta-feira 13:15 as 14:15
  {
    id: 3,
    nome: "LAIANI NOVAES DOS SANTOS",
    cpf: "11085898555", // ✓ Confirmado na lista
    dataNascimento: "2013-10-26",
    sexo: "Feminino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Quarta", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 fem", "futsal sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.8,
    foto: "",
  },
  {
    id: 4,
    nome: "LORENA DE JESUS OLIVEIRA",
    cpf: "10222598573", // ✓ Confirmado na lista
    dataNascimento: "2013-07-24",
    sexo: "Feminino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Quarta", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.2,
    foto: "",
  },
  {
    id: 5,
    nome: "HELOÁ PORTO LIBARINO",
    cpf: "10882216538", // ✓ Confirmado na lista
    dataNascimento: "2015-02-14",
    sexo: "Feminino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Quarta", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.5,
    foto: "",
  },

  // ==================== BALEADO FEMININO - SUB 15 ====================
  // Quarta-feira 14:15 as 15:15
  {
    id: 6,
    nome: "NICOLE FERNANDES ALVES",
    cpf: "10164717501", // ✓ Confirmado na lista
    dataNascimento: "2012-03-04",
    sexo: "Feminino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 fem", "basquete sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 9.0,
    foto: "",
  },
  {
    id: 7,
    nome: "MILENA AGUIAR SANTOS",
    cpf: "10834660547", // ✓ Confirmado na lista
    dataNascimento: "2011-08-07",
    sexo: "Feminino",
    turma: "8º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 fem", "basquete sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.0,
    foto: "",
  },
  {
    id: 8,
    nome: "TAINARA MOUTINHO SILVA",
    cpf: "10187692505", // ✓ Confirmado na lista
    dataNascimento: "2011-06-24",
    sexo: "Feminino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: [
      "baleado sub-15 fem",
      "basquete sub-15 fem",
      "futsal sub-15 fem",
    ],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.5,
    foto: "",
  },
  {
    id: 9,
    nome: "MARIELE SANTOS DE SOUZA",
    cpf: "10103583599", // ✓ Confirmado na lista
    dataNascimento: "2012-09-01",
    sexo: "Feminino",
    turma: "8º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.5,
    foto: "",
  },
  {
    id: 10,
    nome: "EVELYN SANTOS VIANA MOREIRA",
    cpf: "09754726582", // ✓ Confirmado na lista
    dataNascimento: "2012-02-09",
    sexo: "Feminino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.8,
    foto: "",
  },
  {
    id: 11,
    nome: "ELOA SANTOS VIANA MOREIRA",
    cpf: "09754706557", // ✓ Confirmado na lista
    dataNascimento: "2012-02-09",
    sexo: "Feminino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.3,
    foto: "",
  },
  {
    id: 12,
    nome: "CAUANE SANTOS DE SOUSA",
    cpf: "17631665621", // ✓ Confirmado na lista
    dataNascimento: "2012-07-30",
    sexo: "Feminino",
    turma: "8º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.9,
    foto: "",
  },

  // ==================== BALEADO MASCULINO - SUB 13 ====================
  // Segunda-feira 13:15 as 14:15
  {
    id: 13,
    nome: "DARLAN DE OLIVEIRA SANTOS",
    cpf: "10349482535", // ✓ Confirmado na lista
    dataNascimento: "2013-11-06",
    sexo: "Masculino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.2,
    foto: "",
  },
  {
    id: 14,
    nome: "PAULO MATHEUS SOBRINHO OLIVEIRA",
    cpf: "10830483500", // ✓ Confirmado na lista
    dataNascimento: "2013-02-09",
    sexo: "Masculino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.5,
    foto: "",
  },
  {
    id: 15,
    nome: "INACIO PEREIRA AGUIAR",
    cpf: "11204756511", // ✓ Confirmado na lista
    dataNascimento: "2014-04-01",
    sexo: "Masculino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.0,
    foto: "",
  },
  {
    id: 16,
    nome: "KEVEN SANTOS SILVA GOMES",
    cpf: "10117871567", // ✓ Confirmado na lista
    dataNascimento: "2013-11-26",
    sexo: "Masculino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 6.8,
    foto: "",
  },
  {
    id: 17,
    nome: "DAVI BRITO OLIVEIRA",
    cpf: "10737321504", // ✓ Confirmado na lista
    dataNascimento: "2014-10-31",
    sexo: "Masculino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.3,
    foto: "",
  },
  {
    id: 18,
    nome: "LAZARO SOUZA ROCHA",
    cpf: "10632538538", // ✓ Confirmado na lista
    dataNascimento: "2013-05-26",
    sexo: "Masculino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc", "futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.1,
    foto: "",
  },
  {
    id: 19,
    nome: "BRENO SANTOS DE JESUS",
    cpf: "10459917595", // ✓ Confirmado na lista
    dataNascimento: "2014-03-07",
    sexo: "Masculino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc", "futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 6.5,
    foto: "",
  },
  {
    id: 20,
    nome: "JARDIEL CERQUEIRA DA SILVA",
    cpf: "10928993590", // ✓ Confirmado na lista
    dataNascimento: "2015-03-11",
    sexo: "Masculino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 6.9,
    foto: "",
  },
  {
    id: 21,
    nome: "ARTHUR RIBEIRO SANTOS",
    cpf: "10183880528", // ✓ Confirmado na lista
    dataNascimento: "2015-02-05",
    sexo: "Masculino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.4,
    foto: "",
  },

  // ==================== BALEADO MASCULINO - SUB 15 ====================
  // Segunda-feira 14:15 as 15:15
  {
    id: 22,
    nome: "MARCOS MACEDO DOS SANTOS",
    cpf: "10200736590", // ✓ Confirmado na lista
    dataNascimento: "2012-08-11",
    sexo: "Masculino",
    turma: "8º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Segunda", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.8,
    foto: "",
  },
  {
    id: 23,
    nome: "CLEITON OLIVEIRA SANTOS",
    cpf: "12657721508", // ✓ Confirmado na lista
    dataNascimento: "2011-04-11",
    sexo: "Masculino",
    turma: "7º ANO D",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "Segunda", horario: "14h15-15h15" }],
    modalidades: [
      "baleado sub-15 masc",
      "basquete sub-15 masc",
      "futsal sub-15 masc",
    ],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.6,
    foto: "",
  },

  // ==================== HANDEBOL MASCULINO - SUB 13 ====================
  // Quarta-feira 7:15 as 8:15 | Quinta-feira 15:30 as 16:15
  {
    id: 24,
    nome: "LUAN BRITO PAIVA MACEDO",
    cpf: "10166886521", // ✓ Confirmado na lista
    dataNascimento: "2013-06-17",
    sexo: "Masculino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc", "futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.0,
    foto: "",
  },
  {
    id: 25,
    nome: "IGOR DA SILVA LIMA",
    cpf: "09965511586", // ✓ Confirmado na lista
    dataNascimento: "2014-04-29",
    sexo: "Masculino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc", "futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.7,
    foto: "",
  },
  {
    id: 26,
    nome: "HUGO CESAR GONÇALVES SANTOS",
    cpf: "10456469540", // ✓ Confirmado na lista
    dataNascimento: "2014-03-04",
    sexo: "Masculino",
    turma: "7º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.2,
    foto: "",
  },
  {
    id: 27,
    nome: "ELDER SANTOS CAMPOS ROCHA",
    cpf: "10133182509", // ✓ Confirmado na lista
    dataNascimento: "2013-11-27",
    sexo: "Masculino",
    turma: "7º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc", "futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.9,
    foto: "",
  },
  {
    id: 28,
    nome: "RIAN BRITO PAIVA MACEDO",
    cpf: "11075571510", // ✓ Confirmado na lista
    dataNascimento: "2014-06-07",
    sexo: "Masculino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.1,
    foto: "",
  },
  {
    id: 29,
    nome: "GUSTAVO LIMA SANTOS",
    cpf: "13737194513", // ✓ Confirmado na lista
    dataNascimento: "2013-02-26",
    sexo: "Masculino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc", "futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.8,
    foto: "",
  },
  {
    id: 30,
    nome: "JOÃO MIGUEL BRITO PAIVA",
    cpf: "10162725531", // ✓ Confirmado na lista
    dataNascimento: "2013-07-28",
    sexo: "Masculino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.4,
    foto: "",
  },
  {
    id: 31,
    nome: "MAICON WILSON SANTOS VIANA",
    cpf: "10270713506", // ✓ Confirmado na lista
    dataNascimento: "2013-04-19",
    sexo: "Masculino",
    turma: "6º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.0,
    foto: "",
  },

  // ==================== HANDEBOL MASCULINO - SUB 15 ====================
  // Quarta-feira 8:15 as 9:15 | Quinta-feira 16:15 as 17:00
  {
    id: 32,
    nome: "SAMUEL LUCAS RIBEIRO SANTOS",
    cpf: "10183921577", // ✓ Confirmado na lista (CORRIGIDO)
    dataNascimento: "2012-02-24",
    sexo: "Masculino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Quarta", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "16h15-17h00" },
    ],
    modalidades: ["handebol sub-15 masc", "futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.6,
    foto: "",
  },
  {
    id: 33,
    nome: "VINICIUS DE JESUS SANTOS FERREIRA",
    cpf: "09947598519", // ✓ Confirmado na lista
    dataNascimento: "2011-07-19",
    sexo: "Masculino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Quarta", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "16h15-17h00" },
    ],
    modalidades: ["handebol sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.3,
    foto: "",
  },
  {
    id: 34,
    nome: "CAUAN VITOR ROCHA VIEIRA",
    cpf: "08544836593", // ✓ Confirmado na lista
    dataNascimento: "2012-08-23",
    sexo: "Masculino",
    turma: "8º ANO B",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [
      { dia: "Quarta", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "16h15-17h00" },
    ],
    modalidades: ["handebol sub-15 masc", "futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.0,
    foto: "",
  },
  {
    id: 35,
    nome: "VINICIUS MOTA SANTOS",
    cpf: "09964643527", // ✓ Confirmado na lista
    dataNascimento: "2011-05-06",
    sexo: "Masculino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Quarta", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "16h15-17h00" },
    ],
    modalidades: ["handebol sub-15 masc", "futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },

  // ==================== HANDEBOL MASCULINO - SUB 17 ====================
  // Quarta-feira 9:30 as 10:30 | Quinta-feira 16:15 as 17:00
  {
    id: 36,
    nome: "DAVI DA SILVA",
    cpf: "10082478554", // ✓ Confirmado na lista
    dataNascimento: "2009-06-26",
    sexo: "Masculino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Quarta", horario: "09h30-10h30" },
      { dia: "Quinta", horario: "16h15-17h00" },
    ],
    modalidades: ["handebol sub-17 masc", "futsal sub-17 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.7,
    foto: "",
  },
  {
    id: 37,
    nome: "RAFIC LIMA FREITAS",
    cpf: "07543283506", // ✓ Confirmado na lista
    dataNascimento: "2009-09-04",
    sexo: "Masculino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Quarta", horario: "09h30-10h30" },
      { dia: "Quinta", horario: "16h15-17h00" },
    ],
    modalidades: ["handebol sub-17 masc", "futsal sub-17 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.9,
    foto: "",
  },

  // ==================== HANDEBOL FEMININO - SUB 13 ====================
  // Segunda-feira 7:15 as 8:15 | Quarta-feira 13:15 as 14:15
  {
    id: 38,
    nome: "ANA JULIA PEREIRA SANTOS",
    cpf: "10462029522", // ✓ Confirmado na lista
    dataNascimento: "2014-04-09",
    sexo: "Feminino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["handebol sub-13 fem", "futsal sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.5,
    foto: "",
  },
  {
    id: 39,
    nome: "ELOISA MARTINS DOS SANTOS",
    cpf: "10001347500", // ✓ Confirmado na lista
    dataNascimento: "2013-05-26",
    sexo: "Feminino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["handebol sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.9,
    foto: "",
  },
  {
    id: 40,
    nome: "HEMYLE ALMEIDA RIBEIRO",
    cpf: "09960817555", // ✓ Confirmado na lista
    dataNascimento: "2013-07-09",
    sexo: "Feminino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["handebol sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.0,
    foto: "",
  },

  // ==================== HANDEBOL FEMININO - SUB 15 ====================
  // Segunda-feira 8:15 as 9:15 | Quarta-feira 14:15 as 15:15
  {
    id: 41,
    nome: "BRUNA PEREIRA DA SILVA",
    cpf: "10839167504", // ✓ Confirmado na lista
    dataNascimento: "2012-01-08",
    sexo: "Feminino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["handebol sub-15 fem", "basquete sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.3,
    foto: "",
  },

  // ==================== HANDEBOL FEMININO - SUB 17 ====================
  // Segunda-feira 8:15 as 9:15 | Quarta-feira 14:15 as 15:15
  {
    id: 42,
    nome: "MARIA ELISA DUARTE DOS SANTOS",
    cpf: "10227036506", // ✓ Confirmado na lista
    dataNascimento: "2011-05-13",
    sexo: "Feminino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["handebol sub-17 fem", "futsal sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.5,
    foto: "",
  },
  {
    id: 43,
    nome: "STHEFANI FERREIRA SANTOS",
    cpf: "09985555503", // ✓ Confirmado na lista
    dataNascimento: "2012-11-07",
    sexo: "Feminino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["handebol sub-17 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.6,
    foto: "",
  },
  {
    id: 44,
    nome: "GLEICIA NOVAES DOS SANTOS",
    cpf: "11085862526", // ✓ Confirmado na lista
    dataNascimento: "2011-01-09",
    sexo: "Feminino",
    turma: "Módulo V",
    turno: "NOTURNO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["handebol sub-17 fem", "futsal sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.2,
    foto: "",
  },
  {
    id: 45,
    nome: "MARIA EDUARDA SANTOS DE OLIVEIRA",
    cpf: "57519733807", // ✓ Confirmado na lista
    dataNascimento: "2012-03-11",
    sexo: "Feminino",
    turma: "9º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["handebol sub-17 fem", "futsal sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.1,
    foto: "",
  },
  {
    id: 46,
    nome: "THAIS BRITO PAIVA MACEDO",
    cpf: "10166826545", // ✓ Confirmado na lista
    dataNascimento: "2010-01-13",
    sexo: "Feminino",
    turma: "9º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["handebol sub-17 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },

  // ==================== BASQUETE MASCULINO - SUB 15 ====================
  {
    id: 47,
    nome: "ERICK SOARES CARDOSO",
    cpf: "10314529586", // ✓ Confirmado na lista
    dataNascimento: "2011-03-03",
    sexo: "Masculino",
    turma: "9º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["basquete sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 48,
    nome: "SAMUEL CERQUEIRA GOMES",
    cpf: "10165725575", // ✓ Confirmado na lista
    dataNascimento: "2011-06-20",
    sexo: "Masculino",
    turma: "9º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["basquete sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 49,
    nome: "ROMULO SILVA COSTA",
    cpf: "10066115507", // ✓ Confirmado na lista
    dataNascimento: "2012-05-07",
    sexo: "Masculino",
    turma: "8º ANO A",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["basquete sub-15 masc", "futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 50,
    nome: "DIOGO PEREIRA FERREIRA",
    cpf: "52736489802", // ✓ Confirmado na lista
    dataNascimento: "2011-10-30",
    sexo: "Masculino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["basquete sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 51,
    nome: "MATEUS SILVA SANTOS",
    cpf: "10167738542", // ✓ Confirmado na lista
    dataNascimento: "2010-12-02",
    sexo: "Masculino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["basquete sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 52,
    nome: "YUDE DA SILVA AMORIM",
    cpf: "10628198531", // ✓ Confirmado na lista
    dataNascimento: "2012-07-19",
    sexo: "Masculino",
    turma: "8º ANO A",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["basquete sub-15 masc", "futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 53,
    nome: "GABRIEL SOUZA BRITO",
    cpf: "11792484577", // ✓ Confirmado na lista
    dataNascimento: "2011-03-31",
    sexo: "Masculino",
    turma: "7º ANO D",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["basquete sub-15 masc", "futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 54,
    nome: "BRAYAN PIERRE ALVES SANTOS",
    cpf: "48313455802", // ✓ Confirmado na lista
    dataNascimento: "2011-06-05",
    sexo: "Masculino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["basquete sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 55,
    nome: "PEDRO RAPHAEL COSTA FREITAS",
    cpf: "11695619501", // ✓ Confirmado na lista
    dataNascimento: "2011-07-05",
    sexo: "Masculino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["basquete sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },

  // ==================== BASQUETE FEMININO - SUB 15 ====================
  {
    id: 56,
    nome: "ALICE FIGUEREDO SANTOS",
    cpf: "10887128513", // ✓ Confirmado na lista
    dataNascimento: "2012-02-08",
    sexo: "Feminino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["basquete sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 57,
    nome: "ANA JULIA NOVAIS MORAIS",
    cpf: "11107008573", // ✓ Confirmado na lista
    dataNascimento: "2011-10-15",
    sexo: "Feminino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["basquete sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 58,
    nome: "BRENDA VIANA SANTOS",
    cpf: "09930157514", // ✓ Confirmado na lista
    dataNascimento: "2011-11-30",
    sexo: "Feminino",
    turma: "9º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["basquete sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 59,
    nome: "SOPHIA FERREIRA GOES",
    cpf: "10069234540", // ✓ Confirmado na lista
    dataNascimento: "2012-12-28",
    sexo: "Feminino",
    turma: "8º ANO C",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["basquete sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },

  // ==================== FUTSAL FEMININO - SUB 13 ====================
  {
    id: 60,
    nome: "NICOLE NASCIMENTO DOS SANTOS",
    cpf: "10379060558", // ✓ Confirmado na lista
    dataNascimento: "2014-01-25",
    sexo: "Feminino",
    turma: "7º ANO B",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 61,
    nome: "PRICILA SANTOS",
    cpf: "10167767569", // ✓ Confirmado na lista
    dataNascimento: "2012-10-17",
    sexo: "Feminino",
    turma: "7º ANO B",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 62,
    nome: "THAUANE AMORIM RODRIGUES",
    cpf: "09846497512", // ✓ Confirmado na lista
    dataNascimento: "2013-07-07",
    sexo: "Feminino",
    turma: "7º ANO B",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 63,
    nome: "GRAZIELLE SANTOS PIRES",
    cpf: "13865046533", // ✓ Confirmado na lista
    dataNascimento: "2014-11-08",
    sexo: "Feminino",
    turma: "6º ANO A",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 64,
    nome: "ANA LU SOARES CARDOSO",
    cpf: "10314548530", // ✓ Confirmado na lista
    dataNascimento: "2013-04-29",
    sexo: "Feminino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 65,
    nome: "KATHELEN NICOLE RIBEIRO",
    cpf: "08925791536", // ✓ Confirmado na lista
    dataNascimento: "2015-02-13",
    sexo: "Feminino",
    turma: "6º ANO D",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 66,
    nome: "YASMIN LIMA SANTOS",
    cpf: "13133924567", // ✓ Confirmado na lista
    dataNascimento: "2015-03-26",
    sexo: "Feminino",
    turma: "6º ANO D",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 67,
    nome: "CAROL DOS ANJOS SOUZA",
    cpf: "10499699521", // ✓ Confirmado na lista
    dataNascimento: "2015-02-11",
    sexo: "Feminino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 68,
    nome: "DIULE AGUIAR SILVA",
    cpf: "11025001516", // ✓ Confirmado na lista
    dataNascimento: "2014-05-09",
    sexo: "Feminino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 69,
    nome: "TALITA SILVA LIMA",
    cpf: "10046563512", // ✓ Confirmado na lista
    dataNascimento: "2013-05-13",
    sexo: "Feminino",
    turma: "7º ANO A",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },

  // ==================== FUTSAL FEMININO - SUB 15 ====================
  {
    id: 70,
    nome: "JULIA MOREIRA SANTOS",
    cpf: "09953766541", // ✓ Confirmado na lista
    dataNascimento: "2011-11-28",
    sexo: "Feminino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 71,
    nome: "MARIA GABRIELLE CARVALHO ARAUJO",
    cpf: "09933157558", // ✓ Confirmado na lista
    dataNascimento: "2012-11-23",
    sexo: "Feminino",
    turma: "8º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 72,
    nome: "ARIELA SANTOS SILVA",
    cpf: "10494434546", // ✓ Confirmado na lista
    dataNascimento: "2012-11-19",
    sexo: "Feminino",
    turma: "8º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 73,
    nome: "LORENA OLIVEIRA DE JESUS",
    cpf: "10155639536", // ✓ Confirmado na lista
    dataNascimento: "2012-08-10",
    sexo: "Feminino",
    turma: "8º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 74,
    nome: "MARIBEL DOS SANTOS SILVA",
    cpf: "10172651514", // ✓ Confirmado na lista
    dataNascimento: "2013-10-01",
    sexo: "Feminino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 75,
    nome: "ELOA VIANA DOS SANTOS",
    cpf: "10143960504", // ✓ Confirmado na lista
    dataNascimento: "2012-12-02",
    sexo: "Feminino",
    turma: "8º ANO B",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 76,
    nome: "LAIS SILVA DOS SANTOS",
    cpf: "10143336525", // ✓ Confirmado na lista
    dataNascimento: "2013-08-07",
    sexo: "Feminino",
    turma: "8º ANO B",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },

  // ==================== FUTSAL MASCULINO - SUB 13 ====================
  {
    id: 77,
    nome: "WANDERSON OLIVEIRA PAIVA",
    cpf: "10457247509", // ✓ Confirmado na lista
    dataNascimento: "2014-08-04",
    sexo: "Masculino",
    turma: "6º ANO A",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 78,
    nome: "DAVI DOS SANTOS PEREIRA",
    cpf: "08524983574", // ✓ Confirmado na lista
    dataNascimento: "2013-04-14",
    sexo: "Masculino",
    turma: "6º ANO A",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 79,
    nome: "ADRYAN SOARES LOPES",
    cpf: "10044961502", // ✓ Confirmado na lista
    dataNascimento: "2014-01-20",
    sexo: "Masculino",
    turma: "6º ANO D",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 80,
    nome: "LUAN COSTA CHAGAS",
    cpf: "09947421503", // ✓ Confirmado na lista
    dataNascimento: "2013-07-02",
    sexo: "Masculino",
    turma: "7º ANO A",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 81,
    nome: "JOHAN PABLO SOUSA OLIVEIRA",
    cpf: "10113811500", // ✓ Confirmado na lista
    dataNascimento: "2014-02-23",
    sexo: "Masculino",
    turma: "7º ANO A",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 82,
    nome: "HADRIAN JUNIOR DE SOUSA CARDOSO",
    cpf: "10133697509", // ✓ Confirmado na lista
    dataNascimento: "2014-01-24",
    sexo: "Masculino",
    turma: "7º ANO A",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 83,
    nome: "BERNARDO BERNARDINO DE SOUSA",
    cpf: "10911623523", // ✓ Confirmado na lista
    dataNascimento: "2014-12-23",
    sexo: "Masculino",
    turma: "6º ANO A",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 84,
    nome: "THALES SANTANA SOUSA",
    cpf: "10879397551", // ✓ Confirmado na lista
    dataNascimento: "2014-10-12",
    sexo: "Masculino",
    turma: "6º ANO A",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 85,
    nome: "ARTHUR SANTOS SILVA",
    cpf: "12641694506", // ✓ Confirmado na lista
    dataNascimento: "2014-09-13",
    sexo: "Masculino",
    turma: "6º ANO D",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 86,
    nome: "RIAN SANTOS PORTO",
    cpf: "10837470536", // ✓ Confirmado na lista
    dataNascimento: "2014-04-22",
    sexo: "Masculino",
    turma: "6º ANO D",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 87,
    nome: "EIKE OLIVEIRA NASCIMENTO",
    cpf: "10122527526", // ✓ Confirmado na lista
    dataNascimento: "2015-01-11",
    sexo: "Masculino",
    turma: "6º ANO A",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 88,
    nome: "DAVI LUIS MASCARENHAS BRITO",
    cpf: "09973536517", // ✓ Confirmado na lista
    dataNascimento: "2014-07-23",
    sexo: "Masculino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 89,
    nome: "ERIC BRITO SANTOS",
    cpf: "10084498579", // ✓ Confirmado na lista
    dataNascimento: "2013-11-10",
    sexo: "Masculino",
    turma: "7º ANO A",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },

  // ==================== FUTSAL MASCULINO - SUB 15 ====================
  {
    id: 90,
    nome: "PEDRO RAPHAEL COSTA FREITAS",
    cpf: "116.956.195-01", // ✓ Confirmado na lista (NÃO ENCONTRADO NA LISTA - MANTIDO)
    dataNascimento: "2011-07-04",
    sexo: "Masculino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 91,
    nome: "BRENO CHAVES DOS SANTOS",
    cpf: "10106113569", // ✓ Confirmado na lista
    dataNascimento: "2012-02-11",
    sexo: "Masculino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 92,
    nome: "HADRIEL PEREIRA SANTOS",
    cpf: "10462039595", // ✓ Confirmado na lista
    dataNascimento: "2012-02-19",
    sexo: "Masculino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 93,
    nome: "PEDRO DOS SANTOS SILVA",
    cpf: "10180128507", // ✓ Confirmado na lista
    dataNascimento: "2012-06-23",
    sexo: "Masculino",
    turma: "7º ANO B",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 94,
    nome: "RAFAEL BARBOSA DE SOUSA",
    cpf: "09140717500", // ✓ Confirmado na lista
    dataNascimento: "2012-10-02",
    sexo: "Masculino",
    turma: "8º ANO B",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 95,
    nome: "IZAQUE SILVA SANTOS",
    cpf: "10065566564", // ✓ Confirmado na lista
    dataNascimento: "2012-06-29",
    sexo: "Masculino",
    turma: "8º ANO C",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 96,
    nome: "MICAEL DA SILVA SANTOS",
    cpf: "10171021550", // ✓ Confirmado na lista
    dataNascimento: "2012-11-06",
    sexo: "Masculino",
    turma: "8º ANO B",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 97,
    nome: "MAXSUEL SILVA FREITAS",
    cpf: "10596783574", // ✓ Confirmado na lista
    dataNascimento: "2011-05-10",
    sexo: "Masculino",
    turma: "7º ANO D",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 98,
    nome: "NATAN PAIVA MACEDO",
    cpf: "10166859559", // ✓ Confirmado na lista
    dataNascimento: "2012-01-30",
    sexo: "Masculino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 99,
    nome: "LUIS FELIPE SILVA DE OLIVEIRA",
    cpf: "10204452546", // ✓ Confirmado na lista
    dataNascimento: "2012-06-07",
    sexo: "Masculino",
    turma: "8º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA RURAL",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 100,
    nome: "LYONEL RIQUELME PEREIRA RIBEIRO",
    cpf: "10242485502", // ✓ Confirmado na lista
    dataNascimento: "2012-08-15",
    sexo: "Masculino",
    turma: "8º ANO A",
    turno: "MATUTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 101,
    nome: "LUAN NUNES SILVA",
    cpf: "10138871582", // ✓ Confirmado na lista
    dataNascimento: "2012-06-09",
    sexo: "Masculino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 102,
    nome: "WESLEY RIBEIRO LISBOA",
    cpf: "08952189507", // ✓ Confirmado na lista
    dataNascimento: "2012-01-27",
    sexo: "Masculino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },

  // ==================== FUTSAL MASCULINO - SUB 17 ====================
  {
    id: 103,
    nome: "MARCOS BARRETO DA SILVA",
    cpf: "09987369537", // ✓ Confirmado na lista
    dataNascimento: "2009-03-31",
    sexo: "Masculino",
    turma: "9º ANO C",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-17 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
  {
    id: 104,
    nome: "JULIO CESAR SOUZA DA SILVA",
    cpf: "12793160555", // ✓ Confirmado na lista
    dataNascimento: "2010-08-03",
    sexo: "Masculino",
    turma: "9º ANO C",
    turno: "VESPERTINO",
    localidade: "BARRA NOVA",
    diasTreino: [{ dia: "", horario: "" }],
    modalidades: ["futsal sub-17 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
];

// Exportar para uso em outros arquivos
if (typeof module !== "undefined" && module.exports) {
  module.exports = ALUNOS_CADASTRADOS;
}
