// alunos.js - Dados dos alunos cadastrados
// Data de referência: 31/12/2026

const ALUNOS_CADASTRADOS = [
  // ==================== VOLEI MISTO - SUB 15/17 ====================
  // Segunda-feira 9:30 as 10:50
  {
    id: 1,
    nome: "EMERSON PEREIRA SILVA",
    cpf: "10086297589",
    dataNascimento: "2013-02-29",
    sexo: "Masculino",
    turma: "8º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Segunda", horario: "09h30-10h50" }],
    modalidades: ["vôlei misto"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.5,
    foto: "",
  },
  {
    id: 2,
    nome: "LUCIELE SANTOS OLIVEIRA",
    cpf: "86484219508",
    dataNascimento: "2011-05-14",
    sexo: "Feminino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Segunda", horario: "09h30-10h50" }],
    modalidades: ["vôlei misto"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 9.0,
    foto: "",
  },

  // ==================== BALEADO FEMININO - SUB 13 ====================
  // Quarta-feira 13:15 as 14:15
  {
    id: 3,
    nome: "LAIANI NOVAES DOS SANTOS",
    cpf: "11085898555",
    dataNascimento: "2013-10-26",
    sexo: "Feminino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Quarta", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.8,
    foto: "",
  },
  {
    id: 4,
    nome: "LORENA DE JESUS OLIVEIRA",
    cpf: "10222598573",
    dataNascimento: "2013-07-24",
    sexo: "Feminino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Quarta", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.2,
    foto: "",
  },
  {
    id: 5,
    nome: "HELOÁ PORTO LIBARINO",
    cpf: "10882216538",
    dataNascimento: "2015-02-14",
    sexo: "Feminino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Quarta", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.5,
    foto: "",
  },

  // ==================== BALEADO FEMININO - SUB 15 ====================
  // Quarta-feira 14:15 as 15:15
  {
    id: 6,
    nome: "NICOLE FERNANDES ALVES",
    cpf: "10164717501",
    dataNascimento: "2012-03-04",
    sexo: "Feminino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 9.0,
    foto: "",
  },
  {
    id: 7,
    nome: "MILENA AGUIAR SANTOS",
    cpf: "10834660547",
    dataNascimento: "2011-08-07",
    sexo: "Feminino",
    turma: "8º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.0,
    foto: "",
  },
  {
    id: 8,
    nome: "TAINARA MOUTINHO SILVA",
    cpf: "10187692505",
    dataNascimento: "2011-06-24",
    sexo: "Feminino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.5,
    foto: "",
  },
  {
    id: 9,
    nome: "MARIELE SANTOS DE SOUZA",
    cpf: "10103583599",
    dataNascimento: "2012-09-01",
    sexo: "Feminino",
    turma: "8º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.5,
    foto: "",
  },
  {
    id: 10,
    nome: "EVELYN SANTOS VIANA MOREIRA",
    cpf: "09754726582",
    dataNascimento: "2012-02-09",
    sexo: "Feminino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.8,
    foto: "",
  },
  {
    id: 11,
    nome: "ELOA SANTOS VIANA MOREIRA",
    cpf: "09754706557",
    dataNascimento: "2012-02-09",
    sexo: "Feminino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.3,
    foto: "",
  },
  {
    id: 12,
    nome: "CAUANE SANTOS DE SOUSA",
    cpf: "17631665621",
    dataNascimento: "2012-07-30",
    sexo: "Feminino",
    turma: "8º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Quarta", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.9,
    foto: "",
  },

  // ==================== BALEADO MASCULINO - SUB 13 ====================
  // Segunda-feira 13:15 as 14:15
  {
    id: 13,
    nome: "DARLAN DE OLIVEIRA SANTOS",
    cpf: "10349482535",
    dataNascimento: "2013-01-06",
    sexo: "Masculino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.2,
    foto: "",
  },
  {
    id: 14,
    nome: "PAULO MATHEUS SOBRINHO OLIVEIRA",
    cpf: "10830483500",
    dataNascimento: "2013-02-09",
    sexo: "Masculino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.5,
    foto: "",
  },
  {
    id: 15,
    nome: "INACIO PEREIRA AGUIAR",
    cpf: "11204756511",
    dataNascimento: "2014-04-01",
    sexo: "Masculino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.0,
    foto: "",
  },
  {
    id: 16,
    nome: "KEVEN SANTOS SILVA GOMES",
    cpf: "10117871567",
    dataNascimento: "2013-11-26",
    sexo: "Masculino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 6.8,
    foto: "",
  },
  {
    id: 17,
    nome: "DAVI BRITO OLIVEIRA",
    cpf: "10737321504",
    dataNascimento: "2014-10-31",
    sexo: "Masculino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.3,
    foto: "",
  },
  {
    id: 18,
    nome: "LAZARO SOUZA ROCHA",
    cpf: "10632538538",
    dataNascimento: "2013-05-26",
    sexo: "Masculino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.1,
    foto: "",
  },
  {
    id: 19,
    nome: "BRENO SANTOS DE JESUS",
    cpf: "10459917595",
    dataNascimento: "2014-03-07",
    sexo: "Masculino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 6.5,
    foto: "",
  },
  {
    id: 20,
    nome: "JARDIEL CERQUEIRA DA SILVA",
    cpf: "10928993590",
    dataNascimento: "2015-03-11",
    sexo: "Masculino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 6.9,
    foto: "",
  },
  {
    id: 21,
    nome: "ARTHUR RIBEIRO SANTOS",
    cpf: "10183880528",
    dataNascimento: "2015-02-05",
    sexo: "Masculino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Segunda", horario: "13h15-14h15" }],
    modalidades: ["baleado sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.4,
    foto: "",
  },

  // ==================== BALEADO MASCULINO - SUB 15 ====================
  // Segunda-feira 14:15 as 15:15
  {
    id: 22,
    nome: "MARCOS MACEDO DOS SANTOS",
    cpf: "10200736590",
    dataNascimento: "2012-08-11",
    sexo: "Masculino",
    turma: "8º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Segunda", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.8,
    foto: "",
  },
  {
    id: 23,
    nome: "CLEITON OLIVEIRA SANTOS",
    cpf: "12657721508",
    dataNascimento: "2011-04-11",
    sexo: "Masculino",
    turma: "7º ANO D",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [{ dia: "Segunda", horario: "14h15-15h15" }],
    modalidades: ["baleado sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.6,
    foto: "",
  },

  // ==================== HANDEBOL MASCULINO - SUB 13 ====================
  // Quarta-feira 7:15 as 8:15 | Quinta-feira 15:30 as 16:15
  {
    id: 24,
    nome: "LUAN BRITO PAIVA MACEDO",
    cpf: "10166886521",
    dataNascimento: "2013-06-17",
    sexo: "Masculino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.0,
    foto: "",
  },
  {
    id: 25,
    nome: "IGOR DA SILVA LIMA",
    cpf: "09965511586",
    dataNascimento: "2014-04-29",
    sexo: "Masculino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.7,
    foto: "",
  },
  {
    id: 26,
    nome: "HUGO CESAR GONÇALVES SANTOS",
    cpf: "10456469540",
    dataNascimento: "2014-03-04",
    sexo: "Masculino",
    turma: "7º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.2,
    foto: "",
  },
  {
    id: 27,
    nome: "ELDER SANTOS CAMPOS ROCHA",
    cpf: "10133182509",
    dataNascimento: "2013-11-27",
    sexo: "Masculino",
    turma: "7º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.9,
    foto: "",
  },
  {
    id: 28,
    nome: "RIAN BRITO PAIVA MACEDO",
    cpf: "11075571510",
    dataNascimento: "2014-06-07",
    sexo: "Masculino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.1,
    foto: "",
  },
  {
    id: 29,
    nome: "GUSTAVO LIMA SANTOS",
    cpf: "13737194513",
    dataNascimento: "2013-02-26",
    sexo: "Masculino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.8,
    foto: "",
  },
  {
    id: 30,
    nome: "JOÃO MIGUEL BRITO PAIVA",
    cpf: "10162725531",
    dataNascimento: "2013-07-28",
    sexo: "Masculino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.4,
    foto: "",
  },
  {
    id: 31,
    nome: "MAICON WILSON SANTOS VIANA",
    cpf: "10270713506",
    dataNascimento: "2013-04-19",
    sexo: "Masculino",
    turma: "6º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "15h30-16h15" },
    ],
    modalidades: ["handebol sub-13 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.0,
    foto: "",
  },

  // ==================== HANDEBOL MASCULINO - SUB 15 ====================
  // Quarta-feira 8:15 as 9:15 | Quinta-feira 16:15 as 17:00
  {
    id: 32,
    nome: "SAMUEL LUCAS RIBEIRO SANTOS",
    cpf: "09947598519",
    dataNascimento: "2011-07-19",
    sexo: "Masculino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "16h15-17h00" },
    ],
    modalidades: ["handebol sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.6,
    foto: "",
  },
  {
    id: 33,
    nome: "VINICIUS DE JESUS SANTOS FERREIRA",
    cpf: "09947598519",
    dataNascimento: "2011-07-19",
    sexo: "Masculino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "16h15-17h00" },
    ],
    modalidades: ["handebol sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.3,
    foto: "",
  },
  {
    id: 34,
    nome: "CAUAN VITOR ROCHA VIEIRA",
    cpf: "08544836593",
    dataNascimento: "2012-08-23",
    sexo: "Masculino",
    turma: "8º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "16h15-17h00" },
    ],
    modalidades: ["handebol sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.0,
    foto: "",
  },
  {
    id: 35,
    nome: "VINICIUS MOTA SANTOS",
    cpf: "09964643527",
    dataNascimento: "2011-05-06",
    sexo: "Masculino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "16h15-17h00" },
    ],
    modalidades: ["handebol sub-15 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },

  // ==================== HANDEBOL MASCULINO - SUB 17 ====================
  // Quarta-feira 9:30 as 10:30 | Quinta-feira 16:15 as 17:00
  {
    id: 36,
    nome: "DAVI DA SILVA",
    cpf: "10082478554",
    dataNascimento: "2009-06-26",
    sexo: "Masculino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "09h30-10h30" },
      { dia: "Quinta", horario: "16h15-17h00" },
    ],
    modalidades: ["handebol sub-17 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.7,
    foto: "",
  },
  {
    id: 37,
    nome: "RAFIC LIMA FREITAS",
    cpf: "07543283506",
    dataNascimento: "2009-09-14",
    sexo: "Masculino",
    turma: "9º ANO A",
    turno: "MATUTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Quarta", horario: "09h30-10h30" },
      { dia: "Quinta", horario: "16h15-17h00" },
    ],
    modalidades: ["handebol sub-17 masc"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.9,
    foto: "",
  },

  // ==================== HANDEBOL FEMININO - SUB 13 ====================
  // Segunda-feira 7:15 as 8:15 | Quarta-feira 13:15 as 14:15
  {
    id: 38,
    nome: "ANA JULIA PEREIRA SANTOS",
    cpf: "10462029522",
    dataNascimento: "2014-04-09",
    sexo: "Feminino",
    turma: "6º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["handebol sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.5,
    foto: "",
  },
  {
    id: 39,
    nome: "ELOISA MARTINS DOS SANTOS",
    cpf: "10001347500",
    dataNascimento: "2013-05-26",
    sexo: "Feminino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["handebol sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.9,
    foto: "",
  },
  {
    id: 40,
    nome: "HEMYLE ALMEIDA RIBEIRO",
    cpf: "09960817555",
    dataNascimento: "2013-07-09",
    sexo: "Feminino",
    turma: "7º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["handebol sub-13 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.0,
    foto: "",
  },

  // ==================== HANDEBOL FEMININO - SUB 15 ====================
  // Segunda-feira 8:15 as 9:15 | Quarta-feira 14:15 as 15:15
  {
    id: 41,
    nome: "BRUNA PEREIRA DA SILVA",
    cpf: "10839167504",
    dataNascimento: "2012-01-08",
    sexo: "Feminino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["handebol sub-15 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.3,
    foto: "",
  },

  // ==================== HANDEBOL FEMININO - SUB 17 ====================
  // Segunda-feira 8:15 as 9:15 | Quarta-feira 14:15 as 15:15
  {
    id: 42,
    nome: "MARIA ELISA DUARTE DOS SANTOS",
    cpf: "10227036506",
    dataNascimento: "2011-05-13",
    sexo: "Feminino",
    turma: "9º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["handebol sub-17 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.5,
    foto: "",
  },
  {
    id: 43,
    nome: "STHEFANI FERREIRA SANTOS",
    cpf: "09985555503",
    dataNascimento: "2012-11-07",
    sexo: "Feminino",
    turma: "6º ANO B",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["handebol sub-17 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.6,
    foto: "",
  },
  {
    id: 44,
    nome: "GLEICIA NOVAES DOS SANTOS",
    cpf: "11085862526",
    dataNascimento: "2011-01-09",
    sexo: "Feminino",
    turma: "Módulo V",
    turno: "NOTURNO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["handebol sub-17 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 7.2,
    foto: "",
  },
  {
    id: 45,
    nome: "MARIA EDUARDA SANTOS DE OLIVEIRA",
    cpf: "57519733807",
    dataNascimento: "2012-03-11",
    sexo: "Feminino",
    turma: "9º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["handebol sub-17 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.1,
    foto: "",
  },
  {
    id: 46,
    nome: "THAIS BRITO PAIVA MACEDO",
    cpf: "10166826545",
    dataNascimento: "2010-01-13",
    sexo: "Feminino",
    turma: "9º ANO C",
    turno: "VESPERTINO",
    localidade: "ZONA URBANA",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["handebol sub-17 fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    dataInicioSuspensao: null,
    mediaGeral: 8.4,
    foto: "",
  },
];

// Exportar para uso em outros arquivos
if (typeof module !== "undefined" && module.exports) {
  module.exports = ALUNOS_CADASTRADOS;
}
