// Constante com todos os alunos do Centro Educacional de Barra Nova
// ATUALIZADO: CPFs corrigidos conforme planilha oficial

const ALUNOS_CADASTRADOS = [
  // ==================== TURMA I – 6° E 7° ANOS - VESPERTINO (MASCULINO) ====================
  // Horários: Segunda 07h15-08h15 e Quarta 07h15-08h15
  {
    id: 1,
    nome: "ADRYAN SOARES LOPES",
    cpf: "10044961502",
    dataNascimento: "2014-01-19",
    idade: 12,
    sexo: "Masculino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 2,
    nome: "ARTHUR SANTOS SILVA",
    cpf: "2",
    dataNascimento: "2014-09-12",
    idade: 11,
    sexo: "Masculino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 3,
    nome: "ENZO GABRIEL OLIVEIRA PAIVA",
    cpf: "3",
    dataNascimento: "2014-04-30",
    idade: 11,
    sexo: "Masculino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 4,
    nome: "EZEQUIEL TELES NATIVIDADE",
    cpf: "86575836585",
    dataNascimento: "2011-09-29",
    idade: 13,
    sexo: "Masculino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 5,
    nome: "LUAN SILVA SANTANA",
    cpf: "5",
    dataNascimento: "2014-05-30",
    idade: 11,
    sexo: "Masculino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 6,
    nome: "MARCOS VINICIUS SILVA SOUSA",
    cpf: "6",
    dataNascimento: "2013-06-10",
    idade: 12,
    sexo: "Masculino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 7,
    nome: "MATHEUS DA SILVA BONFIM",
    cpf: "7",
    dataNascimento: "2012-04-14",
    idade: 13,
    sexo: "Masculino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 8,
    nome: "DAVI DOS SANTOS DIAS",
    cpf: "8",
    dataNascimento: "2015-02-05",
    idade: 10,
    sexo: "Masculino",
    turma: "6° C",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 9,
    nome: "DAVI LUIS MASCARENHAS BRITO",
    cpf: "9",
    dataNascimento: "2014-07-22",
    idade: 11,
    sexo: "Masculino",
    turma: "6° C",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 10,
    nome: "EDERSON FERNANDES SANTOS",
    cpf: "10",
    dataNascimento: "2014-05-15",
    idade: 11,
    sexo: "Masculino",
    turma: "6° C",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 11,
    nome: "GUILHERME FRANCISCO BARRETO DA SILVA",
    cpf: "11",
    dataNascimento: "2013-08-29",
    idade: 12,
    sexo: "Masculino",
    turma: "6° C",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 12,
    nome: "NEEMIAS SANTOS SOUZA",
    cpf: "12",
    dataNascimento: "2014-08-08",
    idade: 11,
    sexo: "Masculino",
    turma: "6° C",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 13,
    nome: "RONALDO ADRIANO GERMANO DE OLIVEIRA JUNIOR",
    cpf: "13",
    dataNascimento: "2014-01-06",
    idade: 12,
    sexo: "Masculino",
    turma: "6° C",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 14,
    nome: "CARLOS ALBERTO MOUTINHO DA SILVA",
    cpf: "10172065542",
    dataNascimento: "2012-05-08",
    idade: 13,
    sexo: "Masculino",
    turma: "7° C",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 15,
    nome: "LUAN NUNES SILVA",
    cpf: "15",
    dataNascimento: "2012-06-08",
    idade: 13,
    sexo: "Masculino",
    turma: "7° C",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 16,
    nome: "NATANAEL DOS SANTOS SOARES",
    cpf: "16",
    dataNascimento: "2013-02-22",
    idade: 12,
    sexo: "Masculino",
    turma: "7° C",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 17,
    nome: "ABRAAO SANTOS SOUZA",
    cpf: "10174440561",
    dataNascimento: "2014-03-09",
    idade: 11,
    sexo: "Masculino",
    turma: "7° D",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 18,
    nome: "DANILO LIMA DE OLIVEIRA DE JESUS",
    cpf: "18",
    dataNascimento: "2013-12-06",
    idade: 12,
    sexo: "Masculino",
    turma: "7° D",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 19,
    nome: "ERIC BRITO SANTOS",
    cpf: "19",
    dataNascimento: "2013-11-09",
    idade: 12,
    sexo: "Masculino",
    turma: "7° D",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 20,
    nome: "GABRIEL SOUZA BRITO",
    cpf: "20",
    dataNascimento: "2011-03-30",
    idade: 14,
    sexo: "Masculino",
    turma: "7° D",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 21,
    nome: "OLAVO ADRYAN LIRA DA SILVA",
    cpf: "21",
    dataNascimento: "2013-03-16",
    idade: 12,
    sexo: "Masculino",
    turma: "7° D",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 22,
    nome: "ROBERTI SILVA PEREIRA",
    cpf: "22",
    dataNascimento: "2010-12-21",
    idade: 14,
    sexo: "Masculino",
    turma: "7° D",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },

  // ==================== TURMA I – 6° E 7° ANOS - VESPERTINO (FEMININO) ====================
  // Horários: Segunda 08h15-09h15 e Quarta 08h15-09h15
  {
    id: 23,
    nome: "GABRIELLY SANTIAGO OLIVEIRA",
    cpf: "23",
    dataNascimento: "2014-08-18",
    idade: 11,
    sexo: "Feminino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 24,
    nome: "ISABELLA COSTA OLIVEIRA",
    cpf: "07965852535",
    dataNascimento: "2014-07-11",
    idade: 11,
    sexo: "Feminino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 25,
    nome: "JHENIFER SILVA",
    cpf: "25",
    dataNascimento: "2014-04-07",
    idade: 11,
    sexo: "Feminino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 26,
    nome: "LIGIA SOUSA ROCHA",
    cpf: "26",
    dataNascimento: "2015-01-31",
    idade: 10,
    sexo: "Feminino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 27,
    nome: "LIVYA DE OLIVEIRA SOUSA",
    cpf: "10122458532",
    dataNascimento: "2014-05-16",
    idade: 11,
    sexo: "Feminino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 28,
    nome: "MICHELE SOUZA ALVES BORGES",
    cpf: "28",
    dataNascimento: "2013-04-03",
    idade: 12,
    sexo: "Feminino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 29,
    nome: "RAQUEL SILVA COSTA",
    cpf: "29",
    dataNascimento: "2015-03-09",
    idade: 10,
    sexo: "Feminino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 30,
    nome: "SABRINA RAMOS GOMES",
    cpf: "30",
    dataNascimento: "2014-05-12",
    idade: 11,
    sexo: "Feminino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 31,
    nome: "STEFANY PEREIRA LISBOA",
    cpf: "31",
    dataNascimento: "2014-08-23",
    idade: 11,
    sexo: "Feminino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 32,
    nome: "YASMIN LIMA SANTOS",
    cpf: "32",
    dataNascimento: "2015-03-25",
    idade: 10,
    sexo: "Feminino",
    turma: "6° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 33,
    nome: "EMANOELE SANTOS FERREIRA",
    cpf: "33",
    dataNascimento: "2010-04-27",
    idade: 15,
    sexo: "Feminino",
    turma: "6° C",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal aberto fem"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 34,
    nome: "FERNANDA VIEIRA SANTOS LINA",
    cpf: "34",
    dataNascimento: "2014-05-23",
    idade: 11,
    sexo: "Feminino",
    turma: "6° C",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 35,
    nome: "GRAZIELLY DA SILVA ROCHA",
    cpf: "10180089501",
    dataNascimento: "2014-11-11",
    idade: 11,
    sexo: "Feminino",
    turma: "6° C",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 36,
    nome: "MARIA CLAUDIA SILVA VIEIRA",
    cpf: "08937536536",
    dataNascimento: "2014-10-07",
    idade: 11,
    sexo: "Feminino",
    turma: "6° C",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 37,
    nome: "YASMIM SAMILE SOUSA SANTOS",
    cpf: "37",
    dataNascimento: "2012-05-02",
    idade: 13,
    sexo: "Feminino",
    turma: "6° C",
    diasTreino: [
      { dia: "Segunda", horario: "07h15-08h15" },
      { dia: "Quarta", horario: "07h15-08h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 38,
    nome: "JOICE KEVELYN DOS REIS SANTOS",
    cpf: "38",
    dataNascimento: "2011-10-15",
    idade: 13,
    sexo: "Feminino",
    turma: "7° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 39,
    nome: "LARAH MARQUES DOMINGUES",
    cpf: "08927772571",
    dataNascimento: "2014-03-07",
    idade: 11,
    sexo: "Feminino",
    turma: "7° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 40,
    nome: "LUANA ALVES DE OLIVEIRA",
    cpf: "40",
    dataNascimento: "2012-04-20",
    idade: 13,
    sexo: "Feminino",
    turma: "7° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 41,
    nome: "MAISA DA SILVA ALMEIDA",
    cpf: "10155283502",
    dataNascimento: "2010-07-19",
    idade: 15,
    sexo: "Feminino",
    turma: "7° D",
    diasTreino: [
      { dia: "Segunda", horario: "08h15-09h15" },
      { dia: "Quarta", horario: "08h15-09h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },

  // ==================== TURMA I – 6° E 7° ANOS - MATUTINO (MASCULINO) ====================
  // Horários: Segunda 13h15-14h15 e Quarta 13h15-14h15
  {
    id: 42,
    nome: "BERNARDO BERNARDINO DE SOUSA",
    cpf: "42",
    dataNascimento: "2014-12-22",
    idade: 11,
    sexo: "Masculino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 43,
    nome: "EIKE OLIVEIRA NASCIMENTO",
    cpf: "10122527526",
    dataNascimento: "2015-01-10",
    idade: 10,
    sexo: "Masculino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 44,
    nome: "ENZO SOUZA DE OLIVEIRA",
    cpf: "10097718505",
    dataNascimento: "2014-10-06",
    idade: 11,
    sexo: "Masculino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 45,
    nome: "GABRIEL BARBOSA SANTOS",
    cpf: "10469786590",
    dataNascimento: "2014-07-17",
    idade: 11,
    sexo: "Masculino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 46,
    nome: "KEVIN DE OLIVEIRA SILVA",
    cpf: "46",
    dataNascimento: "2014-08-12",
    idade: 11,
    sexo: "Masculino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 47,
    nome: "MICAEL DE JESUS PAIVA",
    cpf: "10897419529",
    dataNascimento: "2014-06-01",
    idade: 11,
    sexo: "Masculino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 48,
    nome: "PEDRO HENRIQUE DE OLIVEIRA SILVA",
    cpf: "10109185595",
    dataNascimento: "2013-06-04",
    idade: 12,
    sexo: "Masculino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 49,
    nome: "PEDRO OLIVEIRA SOUSA",
    cpf: "49",
    dataNascimento: "2015-02-21",
    idade: 10,
    sexo: "Masculino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 50,
    nome: "THALES SANTANA SOUSA",
    cpf: "10879397551",
    dataNascimento: "2014-10-11",
    idade: 11,
    sexo: "Masculino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 51,
    nome: "WANDERSON OLIVEIRA PAIVA",
    cpf: "10457247509",
    dataNascimento: "2014-08-03",
    idade: 11,
    sexo: "Masculino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 52,
    nome: "ALISSON SILVA PINA",
    cpf: "52",
    dataNascimento: "2013-03-02",
    idade: 12,
    sexo: "Masculino",
    turma: "6° B",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 53,
    nome: "LUCAS OLIVEIRA DA SILVA",
    cpf: "53",
    dataNascimento: "2013-05-18",
    idade: 12,
    sexo: "Masculino",
    turma: "6° B",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h15-14h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 54,
    nome: "DAVI DOS SANTOS PEREIRA",
    cpf: "08524983574",
    dataNascimento: "2013-04-13",
    idade: 12,
    sexo: "Masculino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 55,
    nome: "EDUARDO PACHECO PINHEIRO",
    cpf: "55",
    dataNascimento: "2014-03-30",
    idade: 11,
    sexo: "Masculino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 56,
    nome: "GUSTAVO VIANA DE SOUZA",
    cpf: "56",
    dataNascimento: "2013-03-16",
    idade: 12,
    sexo: "Masculino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 57,
    nome: "HADRIAN JUNIOR DE SOUSA CARDOSO",
    cpf: "10133697509",
    dataNascimento: "2014-01-23",
    idade: 11,
    sexo: "Masculino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 58,
    nome: "FABRICIO FEITOZA DA SILVA",
    cpf: "58",
    dataNascimento: "2014-03-22",
    idade: 11,
    sexo: "Masculino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 59,
    nome: "JOHAN PABLO SOUSA OLIVEIRA",
    cpf: "10113811500",
    dataNascimento: "2014-02-22",
    idade: 11,
    sexo: "Masculino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 60,
    nome: "LAZARO ANDRADE PEDRA SANTOS",
    cpf: "10113733518",
    dataNascimento: "2013-07-09",
    idade: 12,
    sexo: "Masculino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 61,
    nome: "LUAN COSTA CHAGAS",
    cpf: "09947421503",
    dataNascimento: "2013-07-01",
    idade: 12,
    sexo: "Masculino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 62,
    nome: "DAVID PACHECO ALVES",
    cpf: "10109027507",
    dataNascimento: "2012-11-25",
    idade: 13,
    sexo: "Masculino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 63,
    nome: "DENISSON ROCHA BARRETO",
    cpf: "10260715506",
    dataNascimento: "2012-06-04",
    idade: 13,
    sexo: "Masculino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 64,
    nome: "FERNANDO SILVA DOS SANTOS",
    cpf: "64",
    dataNascimento: "2013-08-16",
    idade: 12,
    sexo: "Masculino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 65,
    nome: "GUILHERME DO NASCIMENTO SILVA",
    cpf: "10186694504",
    dataNascimento: "2013-02-14",
    idade: 12,
    sexo: "Masculino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 66,
    nome: "IAN PABLO FIGUEIRA DOS SANTOS",
    cpf: "10138799539",
    dataNascimento: "2013-05-27",
    idade: 12,
    sexo: "Masculino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 67,
    nome: "MATEUS ALMEIDA BRITO",
    cpf: "10122111508",
    dataNascimento: "2012-07-27",
    idade: 13,
    sexo: "Masculino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 68,
    nome: "PEDRO DOS SANTOS SILVA",
    cpf: "10180128507",
    dataNascimento: "2012-06-22",
    idade: 13,
    sexo: "Masculino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 69,
    nome: "RAFAEL GOMES BATISTA",
    cpf: "10158526538",
    dataNascimento: "2011-09-10",
    idade: 14,
    sexo: "Masculino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },

  // ==================== TURMA I – 6° E 7° ANOS - MATUTINO (FEMININO) ====================
  // Horários: Segunda 14h15-15h15 e Quarta 14h15-15h15
  {
    id: 70,
    nome: "ANA JULIA SANTOS LOPES",
    cpf: "10840247567",
    dataNascimento: "2014-04-21",
    idade: 11,
    sexo: "Feminino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 71,
    nome: "BRENDA DUARTE DOS SANTOS",
    cpf: "10118030540",
    dataNascimento: "2014-12-24",
    idade: 11,
    sexo: "Feminino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 72,
    nome: "ESTER DE SOUSA DIAS",
    cpf: "10016475569",
    dataNascimento: "2014-07-25",
    idade: 11,
    sexo: "Feminino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 73,
    nome: "GRAZIELLE SANTOS PIRES",
    cpf: "73",
    dataNascimento: "2014-11-07",
    idade: 11,
    sexo: "Feminino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 74,
    nome: "LEILA GOMES CARDOSO",
    cpf: "10138082588",
    dataNascimento: "2014-07-20",
    idade: 11,
    sexo: "Feminino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 75,
    nome: "LHORENA FERREIRA GOMES",
    cpf: "10972297502",
    dataNascimento: "2015-03-17",
    idade: 10,
    sexo: "Feminino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 76,
    nome: "MARIA LUIZA SANTOS PINTO DE ALMEIDA",
    cpf: "10375707581",
    dataNascimento: "2014-04-22",
    idade: 11,
    sexo: "Feminino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 77,
    nome: "NICOLLY DOS SANTOS DAMASCENO",
    cpf: "08177529510",
    dataNascimento: "2014-05-06",
    idade: 11,
    sexo: "Feminino",
    turma: "6° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 78,
    nome: "ANA KELLY FERREIRA DA SILVA",
    cpf: "10123238544",
    dataNascimento: "2014-01-05",
    idade: 12,
    sexo: "Feminino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 79,
    nome: "ANA LAURA SOUSA ROCHA",
    cpf: "79",
    dataNascimento: "2014-01-22",
    idade: 12,
    sexo: "Feminino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 80,
    nome: "CLARISSE SANTOS DE SOUSA",
    cpf: "10064100588",
    dataNascimento: "2014-01-14",
    idade: 12,
    sexo: "Feminino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 81,
    nome: "ERVIA LEMOS SANTOS",
    cpf: "10151004579",
    dataNascimento: "2013-06-21",
    idade: 12,
    sexo: "Feminino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 82,
    nome: "LEILIANE SILVA PEREIRA",
    cpf: "10023768584",
    dataNascimento: "2013-06-22",
    idade: 12,
    sexo: "Feminino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 83,
    nome: "NATALY DOS SANTOS SOUZA",
    cpf: "10171101588",
    dataNascimento: "2013-10-16",
    idade: 12,
    sexo: "Feminino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 84,
    nome: "NICOLE DOS SANTOS NASCIMENTO",
    cpf: "11333112530",
    dataNascimento: "2012-03-06",
    idade: 13,
    sexo: "Feminino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 85,
    nome: "PAMELLA SANTOS FERREIRA",
    cpf: "09947629503",
    dataNascimento: "2013-12-19",
    idade: 12,
    sexo: "Feminino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 86,
    nome: "YASMIN AMORIM DE SOUZA",
    cpf: "10077599500",
    dataNascimento: "2013-07-10",
    idade: 12,
    sexo: "Feminino",
    turma: "7° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 87,
    nome: "GABRIELE NASCIMENTO DA SILVA",
    cpf: "10077772571",
    dataNascimento: "2012-04-27",
    idade: 13,
    sexo: "Feminino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 88,
    nome: "MARIANI CARDOSO DE OLIVEIRA",
    cpf: "88",
    dataNascimento: "2013-12-10",
    idade: 12,
    sexo: "Feminino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 89,
    nome: "MARIBEL DOS SANTOS SILVA",
    cpf: "10172651514",
    dataNascimento: "2013-09-30",
    idade: 12,
    sexo: "Feminino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 90,
    nome: "NICOLE NASCIMENTO",
    cpf: "90",
    dataNascimento: "2014-01-24",
    idade: 11,
    sexo: "Feminino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 91,
    nome: "PRICILA SANTOS",
    cpf: "10167767569",
    dataNascimento: "2012-10-16",
    idade: 13,
    sexo: "Feminino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 92,
    nome: "SABRINA DA SILVA COSTA",
    cpf: "10876718500",
    dataNascimento: "2013-04-27",
    idade: 12,
    sexo: "Feminino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 93,
    nome: "TALITA SILVA LIMA",
    cpf: "10046563512",
    dataNascimento: "2013-05-12",
    idade: 12,
    sexo: "Feminino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 94,
    nome: "THAUANE AMORIM RODRIGUES",
    cpf: "94",
    dataNascimento: "2013-07-06",
    idade: 12,
    sexo: "Feminino",
    turma: "7° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "14h15-15h15" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },

  // Continuando com os próximos alunos nos próximos blocos devido ao tamanho...

  // ==================== TURMA II – 8° E 9° ANOS - MATUTINO (MASCULINO) ====================
  // Horários: Segunda 13h15-14h15 e Quarta 13h45-14h30
  {
    id: 95,
    nome: "BRENO BARRETO OLIVEIRA",
    cpf: "10070429588",
    dataNascimento: "2012-10-22",
    idade: 13,
    sexo: "Masculino",
    turma: "8° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 96,
    nome: "CARLOS ANDRE BRITO TELES",
    cpf: "10155068520",
    dataNascimento: "2010-05-14",
    idade: 15,
    sexo: "Masculino",
    turma: "8° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 97,
    nome: "LYONEL RIQUELME PEREIRA RIBEIRO",
    cpf: "10242485502",
    dataNascimento: "2012-08-14",
    idade: 13,
    sexo: "Masculino",
    turma: "8° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 98,
    nome: "ROMULO SILVA COSTA",
    cpf: "10066115507",
    dataNascimento: "2012-05-06",
    idade: 13,
    sexo: "Masculino",
    turma: "8° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 99,
    nome: "WESLEY GOMES CARDOSO",
    cpf: "10138101558",
    dataNascimento: "2012-06-10",
    idade: 13,
    sexo: "Masculino",
    turma: "8° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 100,
    nome: "YUDE DA SILVA AMORIM",
    cpf: "10628198531",
    dataNascimento: "2012-07-18",
    idade: 13,
    sexo: "Masculino",
    turma: "8° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 101,
    nome: "ALVARO DE SOUSA LIMA PINTO",
    cpf: "101",
    dataNascimento: "2012-05-23",
    idade: 13,
    sexo: "Masculino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 102,
    nome: "ARTHUR SANTOS DE OLIVEIRA",
    cpf: "10126326525",
    dataNascimento: "2012-04-25",
    idade: 13,
    sexo: "Masculino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 103,
    nome: "JOSE CARLOS DA SILVA PEREIRA",
    cpf: "10121991504",
    dataNascimento: "2011-09-18",
    idade: 14,
    sexo: "Masculino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 104,
    nome: "KAIQUE DOS SANTOS PEREIRA",
    cpf: "10191613533",
    dataNascimento: "2012-05-10",
    idade: 13,
    sexo: "Masculino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 105,
    nome: "LUIS AUGUSTO SILVA DE SOUZA",
    cpf: "07546321565",
    dataNascimento: "2013-04-01",
    idade: 12,
    sexo: "Masculino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 106,
    nome: "MATEUS SILVA SANTOS",
    cpf: "10167738542",
    dataNascimento: "2010-12-01",
    idade: 15,
    sexo: "Masculino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 107,
    nome: "MICAEL DA SILVA SANTOS",
    cpf: "10171021550",
    dataNascimento: "2012-11-05",
    idade: 13,
    sexo: "Masculino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 108,
    nome: "NATANIEL SOARES RAMOS DE SOUSA",
    cpf: "108",
    dataNascimento: "2013-03-02",
    idade: 12,
    sexo: "Masculino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 109,
    nome: "PEDRO GUILHERME DE OLIVEIRA LEMOS",
    cpf: "09999428592",
    dataNascimento: "2012-09-26",
    idade: 13,
    sexo: "Masculino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 110,
    nome: "RAFAEL BARBOSA DE SOUSA",
    cpf: "09140717500",
    dataNascimento: "2012-10-01",
    idade: 13,
    sexo: "Masculino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 111,
    nome: "ERIC OLIVEIRA VIANA",
    cpf: "10173924557",
    dataNascimento: "2011-03-16",
    idade: 14,
    sexo: "Masculino",
    turma: "9° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 112,
    nome: "EZEQUIEL SANTOS DE OLIVEIRA",
    cpf: "55119199852",
    dataNascimento: "2012-02-09",
    idade: 13,
    sexo: "Masculino",
    turma: "9° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 113,
    nome: "JOAO PEDRO SILVA DE SOUSA",
    cpf: "12478110504",
    dataNascimento: "2010-11-30",
    idade: 15,
    sexo: "Masculino",
    turma: "9° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 114,
    nome: "JULIO CESAR SILVA PEREIRA",
    cpf: "10015946576",
    dataNascimento: "2011-06-10",
    idade: 14,
    sexo: "Masculino",
    turma: "9° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 115,
    nome: "LUIS DAVI DA SILVA LIMA",
    cpf: "08550423548",
    dataNascimento: "2011-04-23",
    idade: 14,
    sexo: "Masculino",
    turma: "9° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 116,
    nome: "NICOLAS FERNANDES SILVA",
    cpf: "10123449596",
    dataNascimento: "2010-10-01",
    idade: 15,
    sexo: "Masculino",
    turma: "9° A",
    diasTreino: [
      { dia: "Segunda", horario: "13h15-14h15" },
      { dia: "Quarta", horario: "13h45-14h30" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },

  // ==================== TURMA II – 8° E 9° ANOS - MATUTINO (FEMININO) ====================
  // Horários: Segunda 14h15-15h15 e Quarta 16h15-17h00
  {
    id: 117,
    nome: "ANA CLARA BRITO TELES",
    cpf: "10155182579",
    dataNascimento: "2012-07-17",
    idade: 13,
    sexo: "Feminino",
    turma: "8° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 118,
    nome: "DAMARYS DE AMORIM LIMA",
    cpf: "10109459555",
    dataNascimento: "2012-06-11",
    idade: 13,
    sexo: "Feminino",
    turma: "8° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 119,
    nome: "ELOA SANTOS BRITO",
    cpf: "08811678510",
    dataNascimento: "2012-07-10",
    idade: 13,
    sexo: "Feminino",
    turma: "8° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 120,
    nome: "EMANUELLE PINTO LIBARINO",
    cpf: "10167100548",
    dataNascimento: "2012-06-29",
    idade: 13,
    sexo: "Feminino",
    turma: "8° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 121,
    nome: "KETELYN FIGUEREDO MOREIRA",
    cpf: "09938611567",
    dataNascimento: "2013-01-01",
    idade: 12,
    sexo: "Feminino",
    turma: "8° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 122,
    nome: "MARIA GABRIELY DE JESUS SILVA",
    cpf: "09996462579",
    dataNascimento: "2012-10-07",
    idade: 13,
    sexo: "Feminino",
    turma: "8° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 123,
    nome: "ANALU OLIVEIRA",
    cpf: "123",
    dataNascimento: "2013-03-01",
    idade: 12,
    sexo: "Feminino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 124,
    nome: "ELIZABETE MOREIRA AGUIAR",
    cpf: "10178371556",
    dataNascimento: "2012-05-16",
    idade: 13,
    sexo: "Feminino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 125,
    nome: "ELOA VIANA DOS SANTOS",
    cpf: "10143960504",
    dataNascimento: "2012-12-01",
    idade: 13,
    sexo: "Feminino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 126,
    nome: "JADY DE OLIVEIRA FIGUEREDO",
    cpf: "126",
    dataNascimento: "2012-11-17",
    idade: 13,
    sexo: "Feminino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 127,
    nome: "PRISCIELE SOUZA SANTOS",
    cpf: "10071069569",
    dataNascimento: "2012-10-02",
    idade: 13,
    sexo: "Feminino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 128,
    nome: "ROSILANE DOS SANTOS ALMEIDA",
    cpf: "09598165507",
    dataNascimento: "2012-07-31",
    idade: 13,
    sexo: "Feminino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 129,
    nome: "STEFFANY VIANA DE OLIVEIRA",
    cpf: "129",
    dataNascimento: "2012-08-21",
    idade: 13,
    sexo: "Feminino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 130,
    nome: "TALITA MOUTINHO DA SILVA",
    cpf: "10073490504",
    dataNascimento: "2011-10-07",
    idade: 14,
    sexo: "Feminino",
    turma: "8° B",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 131,
    nome: "ANA CLARA FIGUEIRA DOS SANTOS",
    cpf: "10138784507",
    dataNascimento: "2011-04-29",
    idade: 14,
    sexo: "Feminino",
    turma: "9° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 132,
    nome: "ANA FRANCISCA DE OLIVEIRA SILVA",
    cpf: "10109220501",
    dataNascimento: "2012-02-17",
    idade: 13,
    sexo: "Feminino",
    turma: "9° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 133,
    nome: "FERNANDA RODRIGUES DE AGUIAR",
    cpf: "10172925584",
    dataNascimento: "2011-07-04",
    idade: 14,
    sexo: "Feminino",
    turma: "9° A",
    diasTreino: [
      { dia: "Segunda", horario: "14h15-15h15" },
      { dia: "Quarta", horario: "16h15-17h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },

  // ==================== TURMA II – 8° E 9° ANOS - VESPERTINO (MASCULINO) ====================
  // Horários: Terça 07h15-08h15 e Quinta 09h15-10h00
  {
    id: 134,
    nome: "BRUNO LUIS COELHO DOS ANJOS",
    cpf: "09479834570",
    dataNascimento: "2012-05-20",
    idade: 13,
    sexo: "Masculino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 135,
    nome: "EDCARLOS MOITINHO SILVA",
    cpf: "10172174597",
    dataNascimento: "2011-04-08",
    idade: 14,
    sexo: "Masculino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 136,
    nome: "EDRYCK SANTOS DE SOUSA",
    cpf: "10066095557",
    dataNascimento: "2012-07-20",
    idade: 13,
    sexo: "Masculino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 137,
    nome: "IAGO SOUSA BRITO",
    cpf: "08825567545",
    dataNascimento: "2012-08-27",
    idade: 13,
    sexo: "Masculino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 138,
    nome: "IZAQUE SILVA SANTOS",
    cpf: "10065566564",
    dataNascimento: "2012-06-28",
    idade: 13,
    sexo: "Masculino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 139,
    nome: "JADER ALVES",
    cpf: "10123509599",
    dataNascimento: "2012-10-28",
    idade: 13,
    sexo: "Masculino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 140,
    nome: "BRENO CHAVES DOS SANTOS",
    cpf: "10106113569",
    dataNascimento: "2012-02-10",
    idade: 13,
    sexo: "Masculino",
    turma: "9° B",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 141,
    nome: "CLEVISSON AMORIM DE JESUS",
    cpf: "10115775501",
    dataNascimento: "2011-01-09",
    idade: 14,
    sexo: "Masculino",
    turma: "9° B",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 142,
    nome: "FELIPE MARES PEREIRA",
    cpf: "142",
    dataNascimento: "2007-06-07",
    idade: 18,
    sexo: "Masculino",
    turma: "9° B",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 143,
    nome: "LUAN SANTOS AMARAL",
    cpf: "54045287884",
    dataNascimento: "2011-12-28",
    idade: 14,
    sexo: "Masculino",
    turma: "9° B",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 144,
    nome: "ANDRE SILVA LIMA",
    cpf: "86654518543",
    dataNascimento: "2010-01-21",
    idade: 15,
    sexo: "Masculino",
    turma: "9° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 145,
    nome: "GUILHERME DE SOUZA MEDRADO",
    cpf: "10173669506",
    dataNascimento: "2011-05-29",
    idade: 14,
    sexo: "Masculino",
    turma: "9° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 146,
    nome: "HENRIQUE MASCARENHAS BRITO",
    cpf: "09975396585",
    dataNascimento: "2011-11-24",
    idade: 14,
    sexo: "Masculino",
    turma: "9° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 147,
    nome: "IAN DE BRITO SANTOS",
    cpf: "08861500510",
    dataNascimento: "2011-08-10",
    idade: 14,
    sexo: "Masculino",
    turma: "9° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 148,
    nome: "JOAO PEDRO DE OLIVEIRA SOUZA",
    cpf: "10031721567",
    dataNascimento: "2011-09-10",
    idade: 14,
    sexo: "Masculino",
    turma: "9° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 149,
    nome: "JULIO CESAR SOUZA DA SILVA",
    cpf: "149",
    dataNascimento: "2010-08-02",
    idade: 15,
    sexo: "Masculino",
    turma: "9° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 150,
    nome: "MARCOS BARRETO DA SILVA",
    cpf: "09987369537",
    dataNascimento: "2009-03-30",
    idade: 16,
    sexo: "Masculino",
    turma: "9° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 151,
    nome: "RUAN SANTOS SILVA",
    cpf: "10045522545",
    dataNascimento: "2008-10-27",
    idade: 17,
    sexo: "Masculino",
    turma: "9° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 152,
    nome: "WESLEY RIBEIRO LISBOA",
    cpf: "08952189507",
    dataNascimento: "2012-01-26",
    idade: 13,
    sexo: "Masculino",
    turma: "9° C",
    diasTreino: [
      { dia: "Terça", horario: "07h15-08h15" },
      { dia: "Quinta", horario: "09h15-10h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },

  // ==================== TURMA II – 8° E 9° ANOS - VESPERTINO (FEMININO) ====================
  // Horários: Terça 08h15-09h15 e Quinta 10h15-11h00
  {
    id: 153,
    nome: "ADRIELLY DA SILVA SANTOS",
    cpf: "10109378555",
    dataNascimento: "2012-05-17",
    idade: 13,
    sexo: "Feminino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 154,
    nome: "BEATRIZ SOUZA SILVA",
    cpf: "10182991571",
    dataNascimento: "2012-11-03",
    idade: 13,
    sexo: "Feminino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 155,
    nome: "CLARA MARCELA DA SILVA DOS SANTOS",
    cpf: "10129884570",
    dataNascimento: "2010-09-30",
    idade: 15,
    sexo: "Feminino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 156,
    nome: "EMILY VITORIA NOVAES SANTOS",
    cpf: "09400824548",
    dataNascimento: "2013-12-17",
    idade: 12,
    sexo: "Feminino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 157,
    nome: "HELOA DE JESUS CHAGAS",
    cpf: "10166087564",
    dataNascimento: "2011-06-20",
    idade: 14,
    sexo: "Feminino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 158,
    nome: "LARISSA DOS SANTOS ALMEIDA",
    cpf: "09972318583",
    dataNascimento: "2010-06-07",
    idade: 15,
    sexo: "Feminino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 159,
    nome: "LARISSA OLIVEIRA SILVA",
    cpf: "159",
    dataNascimento: "2013-02-21",
    idade: 12,
    sexo: "Feminino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 160,
    nome: "MARCELA DA SILVA BRITO",
    cpf: "10181977532",
    dataNascimento: "2012-08-19",
    idade: 13,
    sexo: "Feminino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 161,
    nome: "PRISCILA ALMEIDA DOS SANTOS",
    cpf: "10051568594",
    dataNascimento: "2011-12-16",
    idade: 14,
    sexo: "Feminino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 162,
    nome: "SOPHIA FERREIRA GOES",
    cpf: "10069234540",
    dataNascimento: "2012-12-27",
    idade: 13,
    sexo: "Feminino",
    turma: "8° C",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 163,
    nome: "AGATHA SOPHIA SANTOS OLIVEIRA",
    cpf: "11313967580",
    dataNascimento: "2012-02-19",
    idade: 13,
    sexo: "Feminino",
    turma: "9° B",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 164,
    nome: "ESTEFANI DOS SANTOS SOUZA",
    cpf: "10143545523",
    dataNascimento: "2010-12-10",
    idade: 15,
    sexo: "Feminino",
    turma: "9° B",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 165,
    nome: "GRAZIELE ALVES LEMOS",
    cpf: "09804189500",
    dataNascimento: "2010-12-10",
    idade: 15,
    sexo: "Feminino",
    turma: "9° B",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 166,
    nome: "LARISSA DOS SANTOS SILVA",
    cpf: "10176249508",
    dataNascimento: "2010-10-08",
    idade: 15,
    sexo: "Feminino",
    turma: "9° B",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 167,
    nome: "MARIA ELISA DUARTE DOS SANTOS",
    cpf: "10227036506",
    dataNascimento: "2011-05-12",
    idade: 14,
    sexo: "Feminino",
    turma: "9° B",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 168,
    nome: "JOYCE OLIVEIRA BRITO",
    cpf: "08811668557",
    dataNascimento: "2011-09-28",
    idade: 14,
    sexo: "Feminino",
    turma: "9° C",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 169,
    nome: "NATIANE LOPES LIMA",
    cpf: "169",
    dataNascimento: "2011-05-07",
    idade: 14,
    sexo: "Feminino",
    turma: "9° C",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
  {
    id: 170,
    nome: "YASMIM SANTOS DE JESUS",
    cpf: "10129846562",
    dataNascimento: "2011-12-14",
    idade: 14,
    sexo: "Feminino",
    turma: "9° C",
    diasTreino: [
      { dia: "Terça", horario: "08h15-09h15" },
      { dia: "Quinta", horario: "10h15-11h00" },
    ],
    modalidades: ["futsal"],
    advertencias: 0,
    suspensoes: 0,
    diasSuspensao: 0,
    mediaGeral: 0,
    foto: "",
  },
];

// Função para calcular idade a partir da data de nascimento
function calcularIdade(dataNascimento) {
  const hoje = new Date();
  const nascimento = new Date(dataNascimento);
  let idade = hoje.getFullYear() - nascimento.getFullYear();
  const mes = hoje.getMonth() - nascimento.getMonth();
  if (mes < 0 || (mes === 0 && hoje.getDate() < nascimento.getDate())) idade--;
  return idade;
}

// Atualizar idades dos alunos
ALUNOS_CADASTRADOS.forEach((aluno) => {
  if (!aluno.idade && aluno.dataNascimento) {
    aluno.idade = calcularIdade(aluno.dataNascimento);
  }
});
